# Generated by Django 4.0.2 on 2022-02-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('certificate', models.CharField(choices=[('U/A', 'U/A'), ('A', 'A')], max_length=3)),
                ('type', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('select_date', models.DateField()),
                ('select_time', models.TimeField()),
                ('Image', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
